"""initial schema

Revision ID: 37090beac0a4
Revises: 
Create Date: 2026-04-06 13:11:45.226412

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '37090beac0a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('images',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('owner_id', sa.String(length=36), nullable=False),
                    sa.Column('storage_key', sa.String(), nullable=False),
                    sa.Column('storage_url', sa.String(), nullable=False),
                    sa.Column('format', sa.String(), nullable=False),
                    sa.Column('width', sa.Integer(), nullable=False),
                    sa.Column('height', sa.Integer(), nullable=False),
                    sa.Column('size_bytes', sa.Integer(), nullable=False),
                    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_images_owner_id'), 'images', ['owner_id'], unique=False)
    op.create_table('transformations',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('source_image_id', sa.String(length=36), nullable=False),
                    sa.Column('pipeline_hash', sa.String(), nullable=False),
                    sa.Column('operations', sa.JSON(), nullable=False),
                    sa.Column('storage_key', sa.String(), nullable=False),
                    sa.Column('storage_url', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['source_image_id'], ['images.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_transformations_source_image_id'), 'transformations', ['source_image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transformations_source_image_id'), table_name='transformations')
    op.drop_table('transformations')
    op.drop_index(op.f('ix_images_owner_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
